#!/usr/bin/env bash

if ! command -v "nix" &> /dev/null; then
    echo "[error] command not found: nix" >&2
    exit 1
fi

exec nix \
    --extra-experimental-features flakes \
    --extra-experimental-features nix-command \
    run --inputs-from . nixpkgs#devenv \
    -- \
    "$@"
