#!/usr/bin/env bash

# https://mich-murphy.com/nixos-tmpfs-installation/
# https://elis.nu/blog/2020/05/nixos-tmpfs-as-root/
# https://elis.nu/blog/2020/06/nixos-tmpfs-as-home/

DRIVE="/dev/nvme0n1"
PARTITION_SUFFIX="p" # suffix to drives that denotes a partition. set to `p` for nvme otherwise empty
LUKS_LABEL="persist-luks"
LUKS_MAP_NAME="persist-luks"
ESP_SIZE="512MiB"
FS_LABEL="persist"

# boot.initrd.luks.devices.${LUKS_MAP_NAME}.device = "/dev/disk/by-label/${RAID_LABEL}";

SCRIPT_NAME=$(basename "${0}")
HAS_FALLTHROUGH_ERROR=0
LOG_FILE=$(mktemp)

err_exit() {
    printf "\n[$SCRIPT_NAME] [err] ${1}"
    exit 1
}

println() {
    printf "\n[${SCRIPT_NAME}] ${1}"
}

assert_fallthrough_error() {
    if [[ "${HAS_FALLTHROUGH_ERROR}" == "1" ]]; then
        err_exit "${1}"
    fi
}

while true; do
    println "Enter LUKS password (input hidden):"
    read -rs PASS1
    println "Confirm LUKS password:"
    read -rs PASS2
    if [[ "${PASS1}" == "${PASS2}" ]]; then
        LUKS_PASS="${PASS1}"
        unset PASS1 PASS2
        break
    else
        println "[err] passwords do not match."
    fi
done

# info dump
println "log file: ${LOG_FILE}"
println "luks encryption: yes"
println "drives:"
    println "  * ${DRIVE}"
println "install boot on: ${DRIVE}"
println "raid partitions:"
println "esp size: ${ESP_SIZE}"

# confirm
println "continue? (y/n): "
read -r ANSWER
case $ANSWER in
    [Yy]* )
        ;;
    [Nn]* )
        exit 0
        ;;
    * )
        echo "Invalid input. Please enter y or n."
        exit 1
        ;;
esac
unset ANSWER

println "checking drive..."
println "  * '${DRIVE}'..."
if [ -e "${DRIVE}" ]; then
    printf " ok!"
else
    printf " missing!"
    HAS_FALLTHROUGH_ERROR=1
fi

assert_fallthrough_error "drive check failed"

#println "checking already open luks... "
#if [ -e "/dev/mapper/${LUKS_MAP_NAME}" ]; then
#    printf "closing... "
#    cryptsetup luksClose "/dev/mapper/${LUKS_MAP_NAME}" &>> "${LOG_FILE}" || err_exit "close luks failed"
#    printf "ok!"
#else
#    printf "skip!"
#fi
#
#println "checking already running raid... "
#if [ -e "${PATH_RAID}" ]; then
#    printf "stopping... "
#    mdadm --stop "${PATH_RAID}" &>> "${LOG_FILE}" || err_exit "stopping raid failed"
#    printf "ok!"
#else
#    printf "skip!"
#fi
#
#println "clearing raid partitions..."
#for TARGET in "${RAID_PARTITION_TARGETS[@]}"; do
#    println "  * '${TARGET}'... "
#    if [ -e "${TARGET}" ]; then
#        printf "removing... "
#        mdadm --zero-superblock "${TARGET}" &>> "${LOG_FILE}" || err_exit "failed to zero raid"
#        printf "ok!"
#    else
#        printf "skip!"
#    fi
#done

println "removing partitions..."
sgdisk --zap-all "${DRIVE}" &>> "${LOG_FILE}" || err_exit " failed!"
printf " ok!"

println "probing... "
partprobe "${DRIVE}" &>> "${LOG_FILE}" || err_exit "failed to probe drive"
printf "ok!"

println "create partitions..."
println "  * '${DRIVE}': "
printf "gpt... "
parted -s "${DRIVE}" -- mklabel gpt &>> "${LOG_FILE}" || err_exit "create gpt failed"
printf "boot... "
parted -s "${DRIVE}" -- mkpart ESP fat32 1MiB "${ESP_SIZE}" &>> "${LOG_FILE}" || err_exit "create esp failed"
printf "persist... "
parted -s "${DRIVE}" -- mkpart primary "${ESP_SIZE}" 100% &>> "${LOG_FILE}" || err_exit "create persist failed"
printf "set esp... "
parted -s "${DRIVE}" -- set 1 esp on &>> "${LOG_FILE}" || err_exit "set esp failed"
printf "ok!"

println "probing... "
partprobe "${DRIVE}" &>> "${LOG_FILE}" || err_exit "failed to probe drive"
printf "ok!"

#println "create raid... "
#echo -n "YES" | mdadm --create --verbose --level=0 --metadata=1.2 --name="${RAID_LABEL}" --raid-devices=${#RAID_PARTITION_TARGETS[@]} "${PATH_RAID}" "${RAID_PARTITION_TARGETS[@]}" &>> "${LOG_FILE}" || err_exit "create raid failed!"
#printf "ok!"

println "setup luks... "
printf "create... "
echo -n "${LUKS_PASS}" | cryptsetup luksFormat -y --label="${LUKS_LABEL}" "${DRIVE}${PARTITION_SUFFIX}2" - &>> "${LOG_FILE}" || err_exit "create luks failed"
printf "open... "
echo -n "${LUKS_PASS}" | cryptsetup luksOpen "${DRIVE}${PARTITION_SUFFIX}2" "${LUKS_MAP_NAME}" - &>> "${LOG_FILE}" || err_exit "open luks failed"
printf "ok!"

println "setup fs... "
printf "esp... "
mkfs.fat -F32 -n "boot" "${DRIVE}${PARTITION_SUFFIX}1" &>> "${LOG_FILE}" || err_exit "failed to setup fs for esp"
printf "persist... "
mkfs.ext4 -F -L "${FS_LABEL}" "/dev/mapper/${LUKS_MAP_NAME}" &>> "${LOG_FILE}" || err_exit "failed to setup fs for '${FS_LABEL}'"
sleep 2
printf "ok!"

# ==
println "creating tmpfs root... "
mount -o mode=775 -t tmpfs none /mnt &>> "${LOG_FILE}" || err_exit "failed to create root tmpfs"
printf "ok!"

println "mounting boot... "
printf "create... "
mkdir -p /mnt/boot &>> "${LOG_FILE}" || err_exit "failed to create '/mnt/boot'"
printf "mount... "
mount -o umask=077 /dev/disk/by-label/boot /mnt/boot &>> "${LOG_FILE}" || err_exit "failed to mount boot"
printf "ok!"

println "setup persist... "
printf "create... "
mkdir -p /mnt/persist &>> "${LOG_FILE}" || err_exit "failed to create '/mnt/persist'"
printf "mount... "
mount "/dev/disk/by-label/${FS_LABEL}" /mnt/persist &>> "${LOG_FILE}" || err_exit "failed to mount '${FS_LABEL}'"
printf "ok!"

setup_persist_dir() {
    println "setup persist for '${1}' -> '/persist${1}'... "
    printf "src... "
    mkdir -p "/mnt/persist${1}" &>> "${LOG_FILE}" || err_exit "failed to create persist for '${1}'"
    printf "dst... "
    mkdir -p "/mnt${1}" &>> "${LOG_FILE}" || err_exit "failed to create persist for '${1}'"
    printf "mount... "
    mount -o bind,fmask=002,dmask=002 "/mnt/persist${1}" "/mnt${1}" &>> "${LOG_FILE}" || err_exit "failed to mount '${1}' for persistance"
}

setup_persist_dir "/nix"
setup_persist_dir "/etc/nixos"
setup_persist_dir "/var/log"

# ==

println "generating config... "
nixos-generate-config --root /mnt &>> "${LOG_FILE}" || err_exit "config generate failed"
printf "postfixing... "
mv /mnt/etc/nixos/configuration.nix /mnt/etc/nixos/.configuration.nix
mv /mnt/etc/nixos/hardware-configuration.nix /mnt/etc/nixos/.hardware-configuration.nix
printf "ok!"

println "stage 1 completed!"
println "run: nixos-install --flake /mnt/etc/nixos#mistylake"
